name: Menu Service Dev CI/CD
on:
  push:
    branches:
      - "main"
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server 성공 !
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/menu-project
            git pull origin main
            rm -rf /home/ubuntu/menu-project/src/main/resources/application.yml
            mkdir -p /home/ubuntu/menu-project/src/main/resources
            touch /home/ubuntu/menu-project/src/main/resources/application.yml
            echo "${{ secrets.YML }}" > /home/ubuntu/menu-project/src/main/resources/application.yml
            ls -l /home/ubuntu/menu-project/src/main/resources/application.yml
            sudo fuser -k -n tcp 8080 || true 
            chmod +x ./gradlew
            ./gradlew clean build
            cd build/libs
            nohup java -jar menu-project-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &